### ISSUE TITLE
Make sure that the "Remember me" checkbox keeps the user logged in for a week

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/timecrack#25]

**Comment by tiagofrancafernandes** [comment]
Good point.

Just read the 'remember' input value on login

The problem are:
The input has the name as `remember_me` but on request, you get via `remember`.
Files:
`resources/views/auth/login.blade.php:30`
`app/Http/Requests/Auth/LoginRequest.php:44`

![image](https://github.com/alextselegidis/timecrack/assets/8310974/c6068e9c-b45f-401e-b58e-92cfab136fc7)
![image](https://github.com/alextselegidis/timecrack/assets/8310974/81ce6e87-1f88-44ba-85d3-f5c827a0a48c)

**Comment by tiagofrancafernandes** [comment]
PR: https://github.com/alextselegidis/timecrack/pull/27

**Comment by alextselegidis** [comment]
This is merged, thanks!
