### ISSUE TITLE
Congratulations to using Laravel

### ISSUE THREAD

**Issue by tiagofrancafernandes** [alextselegidis/timecrack#29]
I saw that most of your projects use CI. 
Sorry, but I hate CI. 
I saw that you work well with him. 
Your projects are cool, but give Laravel a chance. 
There are several bad habits that CI users end up bringing to Laravel when migrating. My suggestion to avoid them is to have good mentoring and/or look for good materials and pay attention to the community.

**Comment by tiagofrancafernandes** [comment]
If want to talk, I am on Telegram and linkedin
https://t.me/tiagofrancafernandes/
https://linkedin.com/in/tiago-php/

**Comment by alextselegidis** [comment]
Hello! 

Thanks for checking out the project repos here on GitHub. 

Feel free to give them a star and follow in order to get development updates.
